# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

queue:
  <<: *default   # queueもproductionと同じDBを使用

cable:
  <<: *default
