default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    pool: 5
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *primary_production

  queue:
    <<: *primary_production

  cable:
    <<: *primary_production
